language: php

dist: xenial

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

jobs:
  include:
    -   php: 7.1
        script:
        - composer install
        - php bin/rexlint
