language: php

dist: xenial

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

jobs:
  include:
    -   php: 7.1
        script:
        - composer install
        - vendor/bin/rexlint .
