language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'

cache:
  directories:
  - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"
  - nodejs -v

script:
  - composer install
  - php bin/rexlint
