language: php

php:
  - '7.1'

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

script:
  - composer install
  - php bin/rexlint tests/fail/json/ > /dev/null 2>&1 ; if [ $? -ne 4 ]; then echo "expected fail" && exit 50; fi
  - php bin/rexlint tests/succeed/
