language: php

php:
  - '7.1'

before_install:
  - phpenv config-rm xdebug.ini || echo "xdebug not available"

script:
  - composer install
  - php bin/rexlint tests/fail/yml/   ; lintstatus=$?; if [ $lintstatus -ne  1 ]; then echo "expected fail, got $lintstatus" && exit 50; fi
  - php bin/rexlint tests/fail/php/   ; lintstatus=$?; if [ $lintstatus -ne  2 ]; then echo "expected fail, got $lintstatus" && exit 50; fi
  - php bin/rexlint tests/fail/json/  ; lintstatus=$?; if [ $lintstatus -ne  4 ]; then echo "expected fail, got $lintstatus" && exit 50; fi
  - php bin/rexlint tests/fail/sql/   ; lintstatus=$?; if [ $lintstatus -ne 16 ]; then echo "expected fail, got $lintstatus" && exit 50; fi
  - php bin/rexlint tests/fail/mixed/ ; lintstatus=$?; if [ $lintstatus -ne  7 ]; then echo "expected fail, got $lintstatus" && exit 50; fi
  - php bin/rexlint tests/succeed/
